language: c
compiler:
  - clang
  - gcc

before_install:
 - sudo add-apt-repository ppa:chris-lea/zeromq -y
 - sudo apt-get update -qq
 - sudo apt-get install intltool
 - sudo apt-get install libzmq3-dev 
 - sudo apt-get install libedit-dev 
 - sudo apt-get install libgrok-dev
 - sh autogen.sh

script: ./configure && make && make check
