language: c
compiler:
  - clang
  - gcc

before_install:
 - sudo add-apt-repository ppa:chris-lea/zeromq
 - sudo apt-get update -qq
 - sudo apt-get install intltool
 - sudo apt-get install zeromq3
 - sh autogen.sh

script: ./configure && make && make check
